### ISSUE TITLE
File upload error

### ISSUE THREAD

**Issue by Akash-Dhoni-Krishnan** [VThang51/ROM_Recovery-Builder#5]
Although its builded completely it doesnt upload showing the below error..

No files were found with the provided path: /home/runner/work/ROM_Recovery-Builder/ROM_Recovery-Builder/unofficialtwrp-merlinx.img. No artifacts will be uploaded.
![image](https://user-images.githubusercontent.com/113037849/235966041-91137f9b-79af-4655-b45d-4dc2a2fa2b12.png)
now where can i download the builded recovery

**Comment by VThang51** [comment]
- Did you edit the "Rename file" and "Upload to Artifacts" sections?
- If not, there may be an error in the server 
- Fix the error, try running again
